using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WebhookDelivery.Domain.Common;
using WebhookDelivery.Application.Abstractions;
using WebhookDelivery.Domain.Deliveries;
using WebhookDelivery.Domain.Endpoints;
using WebhookDelivery.Domain.Events;

namespace WebhookDelivery.Infrastructure.Persistence;

public class WebhookDbContext : DbContext, IUnitOfWork
{
    public WebhookDbContext(DbContextOptions<WebhookDbContext> options) : base(options)
    {
    }

    public DbSet<WebhookEndpoint> Endpoints => Set<WebhookEndpoint>();

    public DbSet<WebhookEvent> Events => Set<WebhookEvent>();

    public DbSet<WebhookDeliveryRecord> Deliveries => Set<WebhookDeliveryRecord>();

    public DbSet<WebhookDeliveryAttemptLog> DeliveryAttempts => Set<WebhookDeliveryAttemptLog>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(WebhookDbContext).Assembly);

        ConfigureApplicationGeneratedKeys(modelBuilder);

        base.OnModelCreating(modelBuilder);
    }

    /// <summary>
    /// Ids are assigned by the domain, in <c>BaseEntity</c>, not by the database.
    ///
    /// EF treats a Guid primary key as store generated by default. Combined with
    /// a constructor that already sets it, that makes EF classify a new child
    /// discovered through a navigation as an existing row and issue an UPDATE
    /// instead of an INSERT. It surfaces as
    /// "Attempted to update or delete an entity that does not exist in the store"
    /// the first time an attempt log is appended to a delivery.
    ///
    /// Declaring the keys as never generated is what makes appending to a child
    /// collection work.
    /// </summary>
    private static void ConfigureApplicationGeneratedKeys(ModelBuilder modelBuilder)
    {
        foreach (var entityType in modelBuilder.Model.GetEntityTypes())
        {
            if (!typeof(BaseEntity).IsAssignableFrom(entityType.ClrType))
            {
                continue;
            }

            modelBuilder.Entity(entityType.ClrType)
                .Property(nameof(BaseEntity.Id))
                .ValueGeneratedNever();
        }
    }
}
