using System.Security.Cryptography;
using WebhookDelivery.Domain.Common;

namespace WebhookDelivery.Domain.Endpoints;

/// <summary>
/// A destination registered by a customer application. Events matching its
/// subscriptions are delivered here.
/// </summary>
public class WebhookEndpoint : BaseEntity
{
    private readonly List<string> _subscribedEvents = [];

    private WebhookEndpoint()
    {
    }

    public WebhookEndpoint(string name, Uri url, IEnumerable<string> subscribedEvents)
    {
        SetName(name);
        SetUrl(url);
        ReplaceSubscriptions(subscribedEvents);

        Secret = GenerateSecret();
        Active = true;
    }

    public string Name { get; private set; } = string.Empty;

    public string Url { get; private set; } = string.Empty;

    /// <summary>
    /// Shared secret used to sign every payload sent to this endpoint. It is
    /// generated by the platform and shown to the customer once.
    /// </summary>
    public string Secret { get; private set; } = string.Empty;

    public bool Active { get; private set; }

    public IReadOnlyCollection<string> SubscribedEvents => _subscribedEvents.AsReadOnly();

    /// <summary>
    /// Consecutive delivery failures. Used to disable endpoints that have been
    /// unreachable for a long time, so a dead customer URL stops consuming
    /// worker capacity forever.
    /// </summary>
    public int ConsecutiveFailures { get; private set; }

    public DateTime? DisabledAt { get; private set; }

    public string? DisabledReason { get; private set; }

    public bool IsSubscribedTo(string eventType) =>
        _subscribedEvents.Contains("*") ||
        _subscribedEvents.Contains(eventType, StringComparer.OrdinalIgnoreCase) ||
        _subscribedEvents.Any(subscription =>
            subscription.EndsWith(".*", StringComparison.Ordinal) &&
            eventType.StartsWith(subscription[..^1], StringComparison.OrdinalIgnoreCase));

    public void Update(string name, Uri url, IEnumerable<string> subscribedEvents)
    {
        SetName(name);
        SetUrl(url);
        ReplaceSubscriptions(subscribedEvents);
        Touch();
    }

    public void Activate()
    {
        Active = true;
        ConsecutiveFailures = 0;
        DisabledAt = null;
        DisabledReason = null;
        Touch();
    }

    public void Deactivate(string? reason = null)
    {
        Active = false;
        DisabledAt = DateTime.UtcNow;
        DisabledReason = reason;
        Touch();
    }

    public string RotateSecret()
    {
        Secret = GenerateSecret();
        Touch();

        return Secret;
    }

    public void RecordSuccess()
    {
        ConsecutiveFailures = 0;
        Touch();
    }

    /// <summary>
    /// Returns true when this failure disabled the endpoint.
    /// </summary>
    public bool RecordFailure(int disableAfterConsecutiveFailures)
    {
        ConsecutiveFailures++;
        Touch();

        if (ConsecutiveFailures < disableAfterConsecutiveFailures || !Active)
        {
            return false;
        }

        Deactivate($"Disabled automatically after {ConsecutiveFailures} consecutive failed deliveries.");

        return true;
    }

    private void SetName(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
        {
            throw new DomainException("Endpoint name is required.");
        }

        Name = name.Trim();
    }

    private void SetUrl(Uri url)
    {
        if (url.Scheme != Uri.UriSchemeHttps && url.Scheme != Uri.UriSchemeHttp)
        {
            throw new DomainException("Endpoint URL must use http or https.");
        }

        Url = url.ToString();
    }

    private void ReplaceSubscriptions(IEnumerable<string> subscribedEvents)
    {
        var normalized = subscribedEvents
            .Where(value => !string.IsNullOrWhiteSpace(value))
            .Select(value => value.Trim())
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();

        if (normalized.Count == 0)
        {
            throw new DomainException("An endpoint must subscribe to at least one event type.");
        }

        _subscribedEvents.Clear();
        _subscribedEvents.AddRange(normalized);
    }

    private static string GenerateSecret() =>
        $"whsec_{Convert.ToHexString(RandomNumberGenerator.GetBytes(32)).ToLowerInvariant()}";
}
